# permissions for end users to edit splitsplacers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splitsplacer-editor-role
rules:
- apiGroups:
  - oai.unisinos
  resources:
  - splitsplacers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oai.unisinos
  resources:
  - splitsplacers/status
  verbs:
  - get
