# permissions for end users to view splits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: split-viewer-role
rules:
- apiGroups:
  - oai.unisinos
  resources:
  - splits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oai.unisinos
  resources:
  - splits/status
  verbs:
  - get
