# permissions for end users to view splitsplacers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splitsplacer-viewer-role
rules:
- apiGroups:
  - oai.unisinos
  resources:
  - splitsplacers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oai.unisinos
  resources:
  - splitsplacers/status
  verbs:
  - get
