apiVersion: v1
kind: ConfigMap
metadata:
  name: bw-random-link-delay
  namespace: oai
  labels:
    "topology": "true"
data:
  topology: |
    {
        "nodes": {
            "node16": {
                "interfaces": ["eth0", "eth1"],
                "core": true
            },
            "node14": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3"],
                "hops": 1
            },
            "node15": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3", "eth4"],
                "hops": 1
            },
            "node3": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3", "eth4"],
                "hops": 2
            },
            "node4": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3"],
                "hops": 2
            },
            "node5": {
                "interfaces": ["eth0", "eth1"],
                "hops": 2
            },
            "node6": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node7": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node8": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node9": {
                "interfaces": ["eth0", "eth1"],
                "hops": 4
            },
            "node10": {
                "interfaces": ["eth0", "eth1", "eth2"],
                "hops": 3
            },
            "node11": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node12": {
                "interfaces": ["eth0", "eth1"],
                "hops": 4
            },
            "node13": {
                "interfaces": ["eth0", "eth1"],
                "hops": 5
            }
        },
        "links": {
            "node-6--node-3": {
                "linkCapacity": 300,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-6",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-3",
                    "interface": "eth2"
                }
            },
            "node-6--node-4": {
                "linkCapacity": 600,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-6",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node-4",
                    "interface": "eth2"
                }
            },
            "node-7--node-3": {
                "linkCapacity": 450,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-7",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-3",
                    "interface": "eth3"
                }
            },
            "node-7--node-5": {
                "linkCapacity": 300,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-7",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node-5",
                    "interface": "eth2"
                }
            },
            "node-8--node-3": {
                "linkCapacity": 600,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-8",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-3",
                    "interface": "eth4"
                }
            },
            "node-9--node-8": {
                "linkCapacity": 450,
                "linkDelay": 0.16725,
                "source": {
                    "node": "node-9",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-8",
                    "interface": "eth1"
                }
            },
            "node-10--node-9": {
                "linkCapacity": 300,
                "linkDelay": 0.16725,
                "source": {
                    "node": "node-10",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node-9",
                    "interface": "eth1"
                }
            },
            "node-10--node-4": {
                "linkCapacity": 600,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-10",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-4",
                    "interface": "eth3"
                }
            },
            "node-11--node-4": {
                "linkCapacity": 450,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-11",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-4",
                    "interface": "eth4"
                }
            },
            "node-11--node-5": {
                "linkCapacity": 300,
                "linkDelay": 0.219975,
                "source": {
                    "node": "node-11",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node-5",
                    "interface": "eth3"
                }
            },
            "node-12--node-11": {
                "linkCapacity": 600,
                "linkDelay": 0.16725,
                "source": {
                    "node": "node-12",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-11",
                    "interface": "eth2"
                }
            },
            "node-13--node-12": {
                "linkCapacity": 450,
                "linkDelay": 0.16725,
                "source": {
                    "node": "node-13",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-12",
                    "interface": "eth1"
                }
            },
            "node-3--node-14": {
                "linkCapacity": 1500,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-3",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-14",
                    "interface": "eth1"
                }
            },
            "node-3--node15": {
                "linkCapacity": 1200,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-3",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth1"
                }
            },
            "node-4--node-1": {
                "linkCapacity": 1500,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-4",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-1",
                    "interface": "eth2"
                }
            },
            "node-4--node15": {
                "linkCapacity": 1500,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-4",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth2"
                }
            },
            "node-5--node-1": {
                "linkCapacity": 1200,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-5",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node-1",
                    "interface": "eth3"
                }
            },
            "node-5--node15": {
                "linkCapacity": 1500,
                "linkDelay": 0.199125,
                "source": {
                    "node": "node-5",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth3"
                }
            },
            "node-14--node16": {
                "linkCapacity": 1500,
                "linkDelay": 2,
                "source": {
                    "node": "node-14",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node16",
                    "interface": "eth0"
                }
            },
            "node15--node16": {
                "linkCapacity": 1200,
                "linkDelay": 2,
                "source": {
                    "node": "node15",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node16",
                    "interface": "eth1"
                }
            }
        }
    }
