apiVersion: oai.unisinos/v1beta1
kind: SplitsPlacer
metadata:
  name: splitsplacer-sample
spec:
  coreIP: 10.233.105.56
  rus:
  - splitName: "managed-split"
    node: "node3"
    topologyConfig: "topology"
