apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "1"
spec:
  coreIP: 10.233.105.56
  ruNode: node6
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "2"
spec:
  coreIP: 10.233.105.56
  ruNode: node7
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "3"
spec:
  coreIP: 10.233.105.56
  ruNode: node8
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "4"
spec:
  coreIP: 10.233.105.56
  ruNode: node10
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "5"
spec:
  coreIP: 10.233.105.56
  ruNode: node9
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "6"
spec:
  coreIP: 10.233.105.56
  ruNode: node11
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "7"
spec:
  coreIP: 10.233.105.56
  ruNode: node12
---
apiVersion: oai.unisinos/v1beta1
kind: Split
metadata:
  name: "8"
spec:
  coreIP: 10.233.105.56
  ruNode: node13
