apiVersion: v1
kind: ConfigMap
metadata:
  name: topology
  namespace: oai
  labels:
    "topology": "true"
data:
  topology: |
    {
        "nodes": {
            "node15": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3"],
                "hops": 1
            },
            "node2": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3", "eth4"],
                "hops": 1
            },
            "node3": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3", "eth4"],
                "hops": 2
            },
            "node14": {
                "interfaces": ["eth0", "eth1", "eth2", "eth3"],
                "hops": 2
            },
            "node5": {
                "interfaces": ["eth0", "eth1"],
                "hops": 2
            },
            "node6": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node7": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node8": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node9": {
                "interfaces": ["eth0", "eth1"],
                "hops": 4
            },
            "node10": {
                "interfaces": ["eth0", "eth1", "eth2"],
                "hops": 3
            },
            "node11": {
                "interfaces": ["eth0", "eth1"],
                "hops": 3
            },
            "node12": {
                "interfaces": ["eth0", "eth1"],
                "hops": 4
            },
            "node13": {
                "interfaces": ["eth0", "eth1"],
                "hops": 5
            },
            "node4": {
                "interfaces": ["eth0", "eth1"],
                "core": true
            }
        },
        "links": {
            "node6--node3": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node6",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node3",
                    "interface": "eth2"
                }
            },
            "node6--node14": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node6",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node14",
                    "interface": "eth2"
                }
            },
            "node7--node3": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node7",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node3",
                    "interface": "eth3"
                }
            },
            "node7--node5": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node7",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node5",
                    "interface": "eth2"
                }
            },
            "node8--node3": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node8",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node3",
                    "interface": "eth4"
                }
            },
            "node9--node8": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node9",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node8",
                    "interface": "eth1"
                }
            },
            "node10--node9": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node10",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node9",
                    "interface": "eth1"
                }
            },
            "node10--node14": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node10",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node14",
                    "interface": "eth3"
                }
            },
            "node11--node14": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node11",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node14",
                    "interface": "eth4"
                }
            },
            "node11--node5": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node11",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node5",
                    "interface": "eth3"
                }
            },
            "node12--node11": {
                "linkCapacity": 300,
                "LinkDelay": 0.25,
                "source": {
                    "node": "node12",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node11",
                    "interface": "eth2"
                }
            },
            "node13--node12": {
                "linkCapacity": 300,
                "LinkDelay": 1,
                "source": {
                    "node": "node13",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node12",
                    "interface": "eth1"
                }
            },
            "node3--node15": {
                "linkCapacity": 1200,
                "LinkDelay": 3,
                "source": {
                    "node": "node3",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth1"
                }
            },
            "node3--node2": {
                "linkCapacity": 1200,
                "LinkDelay": 4,
                "source": {
                    "node": "node3",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node2",
                    "interface": "eth1"
                }
            },
            "node14--node15": {
                "linkCapacity": 1200,
                "LinkDelay": 5,
                "source": {
                    "node": "node14",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth2"
                }
            },
            "node14--node2": {
                "linkCapacity": 1200,
                "LinkDelay": 6,
                "source": {
                    "node": "node14",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node2",
                    "interface": "eth2"
                }
            },
            "node5--node15": {
                "linkCapacity": 1200,
                "LinkDelay": 3,
                "source": {
                    "node": "node5",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node15",
                    "interface": "eth3"
                }
            },
            "node5--node2": {
                "linkCapacity": 1200,
                "LinkDelay": 4,
                "source": {
                    "node": "node5",
                    "interface": "eth1"
                },
                "destination": {
                    "node": "node2",
                    "interface": "eth3"
                }
            },
            "node15--node4": {
                "linkCapacity": 1200,
                "LinkDelay": 2,
                "source": {
                    "node": "node15",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node4",
                    "interface": "eth0"
                }
            },
            "node2--node4": {
                "linkCapacity": 1200,
                "LinkDelay": 3,
                "source": {
                    "node": "node2",
                    "interface": "eth0"
                },
                "destination": {
                    "node": "node4",
                    "interface": "eth1"
                }
            }
        }
    }
